name = "calculator"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Calculator"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
pp.fieldNotation = false
linter.style.multiGoal = false
linter.style.setOption = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0-rc1"

[[lean_lib]]
name = "Calculator"
